# Generated by Django 3.2.6 on 2022-06-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCategory', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('countInStock', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('category', models.ManyToManyField(blank=True, null=True, to='store.ProductCategory')),
            ],
            options={
                'verbose_name': 'Imported Product',
            },
        ),
    ]
