# Generated by Django 3.2.6 on 2022-06-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_tax_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax',
            field=models.IntegerField(default='5:24', unique=True),
            preserve_default=False,
        ),
    ]
