# Generated by Django 3.2.6 on 2022-06-08 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_tax_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
