# Generated by Django 3.2.6 on 2022-06-08 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20220608_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxPercent', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='taxPercent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.taxpercent'),
        ),
    ]
