# Generated by Django 3.2.6 on 2022-06-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20220608_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='taxPercent',
        ),
        migrations.DeleteModel(
            name='TaxPercent',
        ),
    ]
