# Generated by Django 4.0.5 on 2022-06-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220608_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-datetime']},
        ),
    ]
