# Generated by Django 4.0.5 on 2022-06-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_product_countinstock_productinstock_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinstock',
            old_name='unit',
            new_name='count',
        ),
    ]
