# Generated by Django 4.0.5 on 2022-06-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_unit_productinstock_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstock',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productinstock',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productinstock',
            name='sell_price',
            field=models.IntegerField(),
        ),
    ]
