# Generated by Django 4.0.5 on 2022-06-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_productinstock_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstock',
            name='currency_unit',
            field=models.CharField(blank=True, choices=[('$', '$'), ('TL', 'TL'), ('SOM', 'SOM'), ('KON', 'KON')], max_length=32, null=True),
        ),
    ]
