# Generated by Django 3.2.6 on 2022-06-08 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_transfermoney_to_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
