# Generated by Django 4.0.5 on 2022-06-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20220608_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='organization.city'),
        ),
    ]
