# Generated by Django 4.0.5 on 2022-06-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_seller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfermoney',
            name='from_account',
        ),
        migrations.AddField(
            model_name='transfermoney',
            name='money_bank',
            field=models.CharField(choices=[('Money', 'Money'), ('Bank', 'Bank')], default='10:40', max_length=32),
            preserve_default=False,
        ),
    ]
