# Generated by Django 4.0.5 on 2022-06-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_remove_transfermoney_from_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfermoney',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
