# Generated by Django 4.0.5 on 2022-06-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_alter_transfermoney_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfermoney',
            options={'verbose_name': 'Take Money'},
        ),
        migrations.AddField(
            model_name='transfermoney',
            name='currency_unit',
            field=models.CharField(choices=[('$', '$'), ('TL', 'TL'), ('SOM', 'SOM'), ('KON', 'KON')], default=2, max_length=32),
            preserve_default=False,
        ),
    ]
