# Generated by Django 4.0.5 on 2022-06-08 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_productinstock_count_and_more'),
        ('organization', '0011_alter_transfermoney_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Buy Product'},
        ),
        migrations.AddField(
            model_name='transfermoney',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='money_transfer_user', to='store.product'),
            preserve_default=False,
        ),
    ]
