# Generated by Django 4.0.5 on 2022-06-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_tax_customer_alter_invoice_customer_and_more'),
        ('outcome_income', '0006_alter_incomes_customer_alter_outcomes_customer'),
        ('organization', '0014_seller_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.tax'),
        ),
        migrations.AlterField(
            model_name='transfermoney',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_transfer_user', to='invoice.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
