# Generated by Django 4.0.5 on 2022-06-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_alter_orderitem_customer_alter_orderitem_tax_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfermoney',
            options={},
        ),
    ]
