# Generated by Django 4.0.5 on 2022-06-08 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outcome_income', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomecategory',
            old_name='user',
            new_name='seller',
        ),
        migrations.AlterField(
            model_name='incomes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outcome_income.incomecategory'),
        ),
    ]
