# Generated by Django 4.0.5 on 2022-06-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcome_income', '0002_rename_user_incomecategory_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomes',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='outcomes',
            name='bank',
        ),
        migrations.AddField(
            model_name='incomes',
            name='money_bank',
            field=models.CharField(choices=[('Money, Money', 'Bank, Bank')], default='02:06', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outcomes',
            name='money_bank',
            field=models.CharField(choices=[('Money, Money', 'Bank, Bank')], default='02:06', max_length=32),
            preserve_default=False,
        ),
    ]
