# Generated by Django 4.0.5 on 2022-06-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcome_income', '0004_alter_incomes_money_bank_alter_outcomes_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomes',
            name='currency_unit',
            field=models.CharField(choices=[('$', '$'), ('TL', 'TL'), ('SOM', 'SOM'), ('KON', 'KON')], default='02:19', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outcomes',
            name='currency_unit',
            field=models.CharField(choices=[('$', '$'), ('TL', 'TL'), ('SOM', 'SOM'), ('KON', 'KON')], default='02:19', max_length=32),
            preserve_default=False,
        ),
    ]
