# Generated by Django 4.0.5 on 2022-06-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_tax_customer_alter_invoice_customer_and_more'),
        ('outcome_income', '0005_incomes_currency_unit_outcomes_currency_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.customer'),
        ),
        migrations.AlterField(
            model_name='outcomes',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.customer'),
        ),
    ]
