# Generated by Django 4.0.5 on 2022-06-13 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_tax_alter_transfermoney_options_customer_and_more'),
        ('outcome_income', '0006_alter_incomes_customer_alter_outcomes_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.customer'),
        ),
        migrations.AlterField(
            model_name='outcomes',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.customer'),
        ),
    ]
