# Generated by Django 4.0.5 on 2022-06-13 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_seller_date'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldproduct',
            old_name='unit',
            new_name='count',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_payment_bank', to='organization.bank'),
        ),
    ]
