# Generated by Django 4.0.5 on 2022-06-13 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_payment_customer_returnedproduct_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='soldproduct',
            options={},
        ),
    ]
